// import { writable } from 'svelte/store';

// export const editor_val = writable('');
// export const submitting = writable(false);

// export const lightMode = writable(undefined);
export const time_periods = [

    {
        title: 'Europe: The Middle Ages',
        time: '1000 - 1600s',
        bg: '/imgs/med_bg.jpeg',
        content: [
            'Our trail of the compound history of psychedelics starts in the Middle Ages in Europe. People of this time did not have a well defined relationship with psychedelics, and there is certainly speculation and theorising involved in connecting the dots. The first step here is to identify when these interactions took place. Firstly, we do know that some people used psychoactive substances such as mandrake, henbane, and deadly nightshade (belladonna). All of these are highly toxic due to the presence of alkaloids such as scopolamine, atropine or hyoscyamine. Another important interaction people had with psychedelics was accidentally ingesting ergot, which contains psychoactive alkaloids including lysergic acid (LSD). The next question is how and why did these interactions come to be?',

            '$/imgs/med_img_1.jpeg$/imgs/med_img_2.jpeg',

            'The first reason for the intentional use of psychedelics that we can find actual records about is "medicinal" (Pliny documented its use by fortune tellers as far back as ancient Greece). Despite the toxicities, these plants were, and still are, used in the treatment of a variety of conditions. Psychoactive plants were used as love philtres, fertility boosters, and a lot of other ointments, fumigations, potions and concoctions. Here we start to see a very important theme, witchcraft. Known as the ‘witches plant’, henbane had great importance during the Middle Ages, being used by magicians and healers in ritual purifications by smoke as well as in the preparation of concoctions, most notably the ‘flying ointments’. Flying ointments were documented as far back as the 13th century by people like the famous alchemist Albertus Magnus, who wrote about those using “black magic” using Henbane for their rites. It’s thanks to writings like his and others that we know what ingredients went into flying ointments in the middle ages, thus connecting our compound to witches. Exposure to this ointment, applied mainly to the armpits or the genital area, produced the sensation of flying. Administered rectally after smearing on a stick or pole, this is reputedly the reason why witches are often depicted as flying on broomsticks. Such practices were prosecuted by The Church and many witches were imprisoned, tortured and burnt at the stake. It is theorized that despite being taken accidentally, even victims of ergot poisoning were persecuted by The Church. This was likely due to the similarities an observer would see between the symptoms of ergot poisoning and the symptoms of the other psychoactive substances. These included seizures, hallucinations and convulsions. Ergot Rye poisoning is also theorised to be the cause of the \'dancing mania\' that manifested in Europe (Saint Vitus dance). This association with witchcraft played a key role in the stigmatization of psychedelics. And so, to answer the question of how psychedelics came to be demonized, we have to answer the question: Why did The Church start hunting and demonizing witches?',

            '$/imgs/med_img_3.jpeg$/imgs/med_img_5.jpeg',

            'Strangely, the truth is that for a long time witchcraft was often viewed with skepticism, and witches of this era weren’t initially perceived as satanic. It wasn\'t until late the 1500s that the great \'witch hunt\' of Europe began, when  texts such as the witch-hunting textbook “Malleus Maleficarum”, were published . There are two dominant theories about the motives and cause for the witch hunt. The first is about bad weather causing mass hysteria, and the second is  about the economic rivalry between churches. Our focus will be on the latter since it is backed by quantifiable data. Until the 1500s, the Catholic Church had claimed a monopoly on religion. It labeled proponents of other religions “heretics” and either forced their conversion or simply killed them, using inquisitions and crusades. Protestantism emerged as the first truly viable challenger to the Catholic church’s hold on the population. Among both Catholics and Protestants, witch-hunting became a prime way for attracting and appeasing the masses by demonstrating their Satan-fighting prowess. It was the simple strategy of stoking fears about an outside threat and then assuring  people that you, and you alone, can protect them (Sound familiar to politics today?). This concept goes a long way toward explaining not just why witch-hunting mania exploded in Europe, but also why it took hold where it did: Germany. The context here is best summarized by Voltaire, who famously remarked that the Holy Roman Empire was “neither holy, nor Roman, nor an empire”. This implies that the HRE was weakened, and due to a decentralized structure, enforcing Catholicism and rooting out Protestantism was much harder. Thus, now we have the complete picture of how psychedelics were caught in the crossfire of the churches, and how by defining the position of witches in society, they also defined the narrative on psychedelics.',

            '$L/imgs/med_img_4.jpeg',

            'By following the compound history of psychedelics in this setting, we even uncover context about the geo-political conflicts of the time. Humans have sought to fight for power ever since the concept has existed. For their greater goal of maintaining their position, The Catholic Church pushed onto the people a stigmatized view on psychedelics (Similar to how cannabis was criminalized in the US for political goals). From here, we will see how the Church\'s position on the use of psychedelics would go on to have consequences that would dictate their compound history in other cultures and settings.'


        ]

    },
    {
        title: 'Aztec Empire: The New World',
        time: '1510s',
        bg: '/imgs/az_bg_2.jpeg',
        content: [
            'The story now shifts to across the ocean. In many ways, the relationship the people of the Aztec empire of the New World had with psychedelics was a direct inversion of what we just saw in Medieval Europe. Here, psychedelics actually held an important role in society in religious contexts and their use was not only tolerated but in fact integral to several ceremonies. The benefit of analysing this setting is that here we get to see the two juxtaposing views of psychedelics interact with each other. This will not only help us follow the compound history of psychedelics, but also reveal to us the motives and beliefs of the people from both cultures.',

            '$/imgs/az_img_1.jpeg$/imgs/az_img_2.jpeg',

            'Teonanácatl, or more simply known as God\'s Flesh, was a key part of religious activities and rituals in the Aztec capital city of Tenochtitlan. The magic mushrooms allowed those who ingested them to speak directly to God, heal diseases, and even induce sexual ecstacy. Mesoamerican tribes had had a long and deep cultural use of hallucinogens, including Psilocybe mushrooms. These mushrooms were often used to commune with the gods, to divine, and for recreation. Archaeologists have found evidence of ritual use of mushrooms by the Aztecs and Mazatecs as early as 200 AD. Mushroom stones and motifs, statuettes, drawings, and recorded history report mushroom use in Guatemala, Mexico, Colima, and throughout the rest of Central America. This however, changed forever with the invasion of the Spanish conquistadors in 1519.',

            '$/imgs/az_img_3.webp',

            'This usage of magic mushrooms was quickly suppressed by Catholic missionaries, who saw the shakes, convulsions, and ravings of patients who had consumed the mushrooms as communication with the devil. Despite this, usage continued, often in private. The first medical record of humans consuming magic mushrooms dates to the late 1500s, and was written by Fray Bernardino de Sahágun: “They ate mushrooms before dawn when they also drank cacao. They ate the mushrooms with honey and when they began to feel excited due to the effect of the mushrooms, the Indians started dancing, while some were singing and others weeping. Thus was the intoxication produced by the mushrooms. Some Indians who did not care to sing sat down in their rooms, remaining there as if to think.” Natives were punished by death when caught with the mushrooms, and their public use became less common. Here we see the clash of values and beliefs of these two cultures, proxied through our compound. The positions of both factions reflect their values and goal; one seeking spirituality while the other self-righteously carrying out a ‘mission’.  The role of psychedelics for the Aztec people is clear, so the questions to ask here are what role did they play in the goal of the Spanish  and what can this tell us about the setting?',

            'It is no secret that the common European view of the time of indigenous people was that they were inferior culturally, technologically, and religiously. The Spanish conquistadors were essentially sanctioned pirates. Their goals primarily focused on stealing wealth for their country and civilizing the natives with Catholicism. Spain hoped to pacify areas that held extractable natural resources such as iron, tin, copper, salt, silver, gold, etc. Another apparent ambition was to just spread Catholicism (More followers, more tithe, more power). In the papal bull of 1508, Universalis Ecclesiae (Of the Universal Church), Pope Julius II declared that the king of Spain would be the head of the Church in Spain and its empire. Such an empowerment clearly meant that along with Spanish law, governance, language, and culture, the Roman Catholic religion, too, would cross from Europe to the Americas and that the king of Spain would engage in the spread of Christianity to the native peoples of the New World. Thus, while not just for the sake of making the locals subservient to them, there clearly was an economic motive behind the religious conversion. Bringing this context of motivation into the picture tells us why the Spanish Missionaries did what they did. Seeing the natives partake in the use of psychedelics, something the Church considered heresy, served as yet another avenue where they could displace the local culture and religion, and squeeze the natives  into the mold of Spanish culture.',

            '$/imgs/az_img_4.jpeg$/imgs/az_img_5.jpeg',

            'There is a striking parallel here to what the Church did back in the Old World (see section "Medieval Europe"). Once again, the compound history of psychedelics was tied to and shaped by authorities with the ambition of power. Of course, this time the scale was powerful armies invading a foreign land, and if not for the diseases the Europeans brought over with them, who knows how things would have played out. Ultimately, this setting gives us context on several important events that shaped history. Apart from the cultural genocide and death of millions of natives, we see how the compound history of psychedelics changed forever, as their use in the Misoamerica was driven underground and forgotten by the west, waiting to someday be rediscovered.',
        ]

    },
    {
        title: 'North America: Indegenous Tribes',
        time: '1550s ',
        bg: '/imgs/ind_bg.jpeg',
        content: [
            'The word psychedelic didn’t come about until 1956 when psychiatrist Humphrey Osmond was corresponding with novelist Aldous Huxley. Huxley wrote the book Brave New World which incorporated a fictional drug called Soma that was used as an antidepressant and hallucinogenic. Before 1956 most of these drugs were referred to as hallucinogens, which focused on the experience of taking these drugs. The word psychedelic comes from the Greek where it meant “mind-manifesting”. Grinspoon and Baker best defined psychedelics as a drug that does not cause “physical addiction, craving, major physiological disturbances, delirium, disorientation, or amnesia…” but still produces “thought, mood, and perceptual changes otherwise rarely experienced except in dreams, contemplative and religious exaltation, flashes of vivid involuntary memory and acute psychoses”. This definition does not encompass drugs like cocaine, opium, cannabis, etc (Williams). While the word psychedelics didn’t come about until 1956, these types of drugs have been noted since Spanish conquerors touched down in Mexico.',

            'Native Americans have been using these psychedelics, specifically peyote, for thousands of years. In the 1800s, European colonizers became interested in these drugs that Native Americans were using, which will be discussed more in the next period of time. Native Americans primarily used psychedelics in the context of religion. Natives would take ten or twelve of these buttons, or the equivalent in Peyote, within a certain time frame for religious ceremonies. Native Americans did this to such an extent that they have built a high tolerance to the effects of these buttons. These ceremonies tended to last all night during which men would sit in a circle around the fire. They stare at the fire while taking ten to twelve buttons in a certain time frame. They sit quietly and watch the visions of color while intoxicated. The visions were seen as to see visions from gods or those they worship. After the ceremony they go to work as normal, but abstain from eating salt that day. After the Natives migrated to the Kiowa Reservation they found it hard to obtain the buttons as it was native to Rio Grande, so they have been supplied by traders, who obtain it from the valley of Rio Grande. Psychedelics are also thought to have been used in the Ghost Dance rituals. The Ghost Dance was a ritual attempt by Native Americans to end European aggression. It is thought that individuals were in a peyote-induced trance when they performed the dance. Participants of the Ghost Dance thought that the hallucinogenic experience was instrumental to resisting the racialized violence and dispossession they suffered. When the modern-day Native American Church (NAC) was formed in the late 1800s these ceremonies were solidified as a key part of traditions among Native Americans, so much so that peyote was legalized for this purpose alone in 1994.',

            'Very spiritual, ritualistic practices involving shamans, drum circles, and healing',

        ]

    },
    {
        title: 'United States and Germany: Peyote Boom',
        time: '1880 - 1900 ',
        bg: '/imgs/pey_bg.jpeg',
        content: [
            'In the late 1800s, the “peyote boom” was ignited by a man named John Raleigh Briggs. Briggs was the first to publish the effects of mescaline buttons (Bruhn). In this article he wrote of his firsthand experience taking the substance. He claimed his pulse rate jumped from 60 to 90, his breath quickened, and he began to feel dizzy. He claimed that if prompt aid (whiskey, large doses of smelling salts, and a long walk) had not been given he would’ve died. Brigg’s experiment opened a new world of research for this hallucinogen. Several researchers worked to isolate different alkaloids and test those effects. There was a sense of urgency among scientists to make a breakthrough discovery. ',

            'Peyote was hard to acquire so experiments were conducted irregularly. The urgency surrounding this “peyote boom” also allowed for little regard to safety and ethics. Arthur Heffter identified four distinct alkaloids by using human subjects including himself to examine the effects of these alkaloids on humans. Heffter reported seeing hallucinations and a loss of sense of time, but said his intellect remained intact. There were countless other incidents of scientists not following today’s standards of ethics. ',

            'The last report to mention would be by Henry Havelock Ellis. Ellis’s report was published in the Lancet in June 1897 where he described his own experience with the drug. He took three buttons at intervals of one hour each. He, like many others, saw colorful hallucinations, but his brain stayed remarkably clear. Ellis wrote that the drug acted on the body to produce a physiological effect and that the powers attributed to peyote by indigenous users and colonial subjects were false. However, he did say that modern science had to determine if these effects were significant enough to undertake a process in which they could transform peyote into a useful drug and asserted that anyone given the opportunity to take the drug should as it would provide an unforgettable and educational experience. Editors of the British Medical Journal heavily disagreed, stating that the drug is a danger to the public. The editors dismissed Ellis’s claim that there is no danger of “mescal mania” as they noted that while people may begin for intellectual reasons, they could easily become addicted because of the pleasure it brings. They continued to say that the indigenous ceremonies were “mescal orgies" and used the classic late-nineteenth century circular racist logic that Indians were degenerate because they were peyotists, or peyotists because they were degenerate (Dawson). This implied the white savior attitudes that Christian morals and modern science could save them. This review established that indigenous people were fundamentally different, and that civilized folk had much more to lose should they fall prey to the drug.',

        ]

    },
    {
        title: 'Switzerland: LSD - My Problem Child',
        time: '1940 - 1970s',
        bg: '/imgs/lsd_bg.jpeg',
        content: [
            '“LSD - My Problem Child” is a personal narrative which illuminates the journey - sometimes dark, sometimes colorful - of the father of LSD, Albert Hofmann. Hofmann, who passed in 2008, was a grand optimist, but not naively so. Though brimming with passion for his work with natural compounds, his story relays a pragmatist. He was a visionary, in a sense like any chemist hoping to discover substances that might productively touch lives and genuinely make the world a better place. His accidental discovery of LSD filled him with joy for its potential therapeutic applications. In the eighty years which have since passed, this informed hypothesis still has substance to it; substance which has endured waves of sensationalism of the drug, global criminalisation, multi-decade halts on scientific research and stigma that extends both into public and scientific circles. Hofmann cautioned of the pharmakon nature of LSD even in his early days of discovery. Had he anticipated how the drug would spiral from a remedy to an inebriant, he would have been more explicit. But of course, as he has acknowledged, never could he have anticipated how his chemical child would leave the nest a problem child: beloved, detested, misused and misunderstood.',

            'In his 1979 book, which sought to straighten half-truth narratives surrounding LSD, Hofmann wrote “I was now and again assailed by doubts whether the valuable pharmacological and psychic effects of LSD might be outweighed by its dangers and by possible injuries due to misuse. Would LSD become a blessing for humanity, or a curse?” (Hofmann 43). This question is Hofmann’s legacy, one which extends far beyond his individual dilemma and forcefully continues to reverberate amidst the psychedelic renaissance of our present day',

            '$imgs/lsd_img_1.jpeg$imgs/lsd_img_2.jpeg',

            'Hofmann’s career as a research chemist stemmed from his childhood entrancement with the plant world (Hofmann 4). In 1929 he joined a modest staff force at Sandoz Company\'s pharmaceutical-chemical research laboratory in Basel, Switzerland. His work revolved around isolating the active principles of known medicinal plants to produce pure specimens of these substances (Hofmann 7).',
            'In the early 1930’s Hofmann requested permission to research ergot alkaloids (Hofmann 8). For reference, ergot is a fungus derivative that grows on rye and has a history dating to the Middle Ages where it was used by midwives to induce labour and restrict postpartum bleeding (Pollan 22). At the time, this was a novel focus but other American and British labs had begun making headway. Hofmann, who fervently loved his line of work, noticed this industry shift and was motivated to ensure Sandoz would maintain its reputation as a pioneering lab, and develop a leading position in what he believed to be a promising space (Hofmann 8).',
            'This was a flourishing period for the European pharmaceutical industry, among which Switzerland had already created a name for itself. In contrast to neighbouring countries, like France, early 19th century Switzerland had no restrictive patent legislation. This attracted “patent refugees” (French chemists and entrepreneurs) to set up dyestuffs enterprises in Basel, which conveniently borders France and Germany (Stavros, 31).',
            'Basel’s riverside location was useful to both the manufacturing and waste disposal processes associated with dyestuffs. Furthermore, capital-rich Basel had a “rich trading and banking tradition”, an “open cultural climate”, and academic footholds as “an old university town” (Stavros, 31).  These were the foundations upon which the Swiss chemicals sector gained early strength.',
            'However, Switzerland’s growth was limited by its lack of natural resources and its small domestic market. This was precisely the competitive disadvantage which motivated the Swiss-based chemical and Pharma industrialists to focus on “high-value added specialty chemicals produced in small volumes” (Stavros, 31).  Modern European “big Pharma” powerhouses like Roche, Novartis and Merck Serono all fundamentally emerged out of these Swiss circumstances (“A Formula for Success: Inside Swiss Pharma”).',
            'The first-third of the 20th century was a period of momentous chemical and pharmaceutical innovation all across Europe. World War 1 provided capital and an urgent impetus for developing medicine. Transformative breakthroughs with penicillin and insulin during the interwar years kept optimistic eyes, and deep pockets, on the space (“A History of the Pharmaceutical Industry”).',
            'This period came prior to the development of the Nuremberg Principles. These formalised ethical practices in biomedicine in response to the horrific war crimes and Nazi prisoner experiments of World War 2 (Hanley, 33). Though the Nuremberg Principles have been influential towards contemporary ethical regulations, when they were introduced they weren’t universally binding. They also focused mostly on patient rights, including the right to informed consent without coercion. Also, they made explicit that “medical practice should be for the benefit of the patient, and if for research that does not directly benefit the patient, it should not harm the patient” (Hanley, 33). Though the Nuremberg principles weren’t even written during Hofmann’s self-experimentation with LSD (see First Synthesis and Experiments with LSD), they give a sense of European state of affairs pertaining to research and ethical standards in this time period directly prior to their conception.',

            '$imgs/lsd_img_3.jpeg',

            'Hofmann had early success as the first person to synthesize (artificially produce) an ergot alkaloid (Hofmann 12). An inspired and excited Hofmann then began producing new lysergic acid compounds (lysergic acid was the name of the nucleus common to all ergot alkaloids) - ones that he hoped would serve as circulatory and respiratory stimulants. In 1938 he produced the 25th substance in this series: what would eventually become known to the world as LSD. In initial testing on animals nothing notable was observed about this substance, aside from the animals becoming restless, so it was shelved indefinitely and testing was discontinued (Hofmann 13).',
            'However, Hofmann remained drawn to this substance. Curiously, he has never provided a logical explanation as to why, merely that he had “a peculiar presentiment - the feeling that this substance could possess properties other than those established in the first investigations” (Hofmann 15).  So, on April 16th, 1943, five years later, he set out to re-synthesize LSD-25 - guided purely by instinct and curiosity. Despite taking careful precautions,  unbeknownst to him at the time, Hofmann absorbed some of the substance through the skin on his fingertips. He “was interrupted in my work by unusual sensations” (Hofmann 15). Therein, unfolded the world’s first LSD trip: intense, colourful, kaleidoscopic and dreamlike. Astounded by the “extraordinary potency” of the substance, Hofmann knew at this point that he had something special on his hands - literally. ',
            'Ironically, in his account he states “There seemed to be only one way of getting to the bottom of this. I decided on a self-experiment” (Hofmann 16). This is juxtaposed in his very next statement: “Exercising extreme caution, I began the planned series of experiments with the smallest quantity that could be expected to produce some effect”. This illuminates much about scientific working practice in mid-90s Switzerland. Today, self-experiments would be considered reckless, naive, and dangerous at best; malpractice and unethical at worst. Instead of being frowned upon, Hofmann’s self-experiments were soon to be closely replicated by his colleagues. As it turned out, his then conservative administrative dosage was sufficient to produce a trip of completely unanticipated intensity. This trip was Hofmann’s first foray into the unpredictable effects of LSD: a drug which had first led him to a dreamlike state and now propelled him through a short-lived, but fully felt living nightmare.',
            'His assistant got him home on a bicycle, as vehicle use was restricted during the war-time setting. He recalled “objects and pieces of furniture assuming strange, grotesque forms.” His kind, familiar neighbour who bought him milk upon his request (a considered remedy he thought might easen this terrifyingly foreign experience) now appeared in his mind’s eye “a malevolent, insidious witch”. “Even worse than these demonic transformations of the outer world, were the alterations that I perceived in myself, in my inner being. [...] A demon had invaded me, had taken possession of my body, mind, and soul” (Hofmann 17).',
            'Hofmann turned out more than fine. Once the worst of his trip had passed, he was able to enjoy the remainder, and the aftermath. The next morning he woke up to “a sensation of well-being and renewed life” flowing through him. Trivial daily minutia - like eating breakfast, gave him “extraordinary pleasure” and he felt “the world was as if newly created” (Hofmann 18).',

            '$imgs/lsd_img_4.jpeg',

            'Hofmann was excited, and hopeful because to his knowledge, no substance could cause “such dramatic changes in human consciousness and our experience of the inner and outer world” (Hofmann 18). This instinctively led him to imagine LSD would be of great value to specialists in pharmacology, neurology and psychiatry (Hofmann 19). He wrote “As the psychic effects of LSD persist even after it can no longer be detected in the organism, we must assume that LSD is not active as such, but that it rather triggers certain biochemical, neurophysiological, and psychic mechanisms that provoke the inebriated condition and continue in the absence of the active principle. [...] Investigations of the interactions of LSD with brain factors like serotonin and dopamine, are examples of how LSD can serve as a tool in brain research, in the study of the biochemical processes that underlie the psychic functions” (Hofmann 23). This illustrates why Hofmann never imagined LSD would be used beyond medical science, as an inebriant in the drug scene: “Since my self-experiment had revealed LSD in its terrifying, demonic aspect, the last thing I could have expected was that this substance could ever find application as anything approaching a pleasure drug” (Hofmann 19).\
            He could “remember the experience of LSD inebriation in every detail … despite the profound breakdown of the normal world view” (Hofmann 19). He was aware of his active, and self-driven participation in the experiment, but despite this recognition he could not control the experience.\
            LSD left him in “excellent physical and mental condition” (Hofmann 19) - even after a largely scary inebriation - without a hangover.\
            In Hofmann\'s interpretation, the above two properties (awareness during inebriation and no hangover) positioned the drug well for therapeutic applications, especially given further experiments which showed it’s high potency, but low toxicity to humans. In fact, between the time of discovery, the publishing of this book, and even today there is no known lethal dose of LSD for humans.',


            'All this considered, Hofmann then shared his discovery with colleagues and superiors. What followed were a series of self-experiments by his colleagues, animal testing (which indicated LSD’s physchoative effects were apparent in mice, cats, dogs, spiders and apes too), and human-testing on healthy participants which confirmed LSD was non-toxic and also resulted in promising, predominantly positive inebriative experiences (Hofmann 20 - 21).\
            It wasn’t until Sandoz made LSD available to research institutes and physicians in hopes of expediting research for medicinal-psychiatric uses that LSD’s compound history took a turn which Hofmann regretted. At the time, the drug was given the trade name of “Delysid” (Hofmann 33). It was distributed with a comprehensive prospectus outlining all important details and extensive precautions. All this to say it was shared with goodwill and high hopes.\
            Under the precautions it was specifically emphasized that Delysid might intensify pathological mental conditions and hence should be treated with extreme caution in cases of suicidality or psychotic tendency. More importantly, “Delysid should only be administered under strict medical supervision. The supervision should not be discontinued until the effects of the drug have completely worn off” (Hofmann 35).',
            'What unfolded was a radical mismatch of Hofmann’s expectations for LSD’s application and the reality. His expectations draw heavy parallels even with contemporary research on LSD. He believed that LSD’s alteration of the subject’s accustomed world view allowed for a healthy breakdown between the “I-you” barrier. This should seemingly allow for deepened patient-practitioner interactions and enable greater patient susceptibility to psychotherapeutic influence. Simultaneously, LSD showed the unique character of resurfacing suppressed or forgotten experiences (e.g. traumatic events) which “may then become accessible to psychotherapeutic treatment” (Hofmann 35). In short, LSD was not a treatment in itself but an aid in effective psychotherapy - one which might also shorten the duration of treatment due to its intensity. Hofmann candidly acknowledged this as the controversial perspective it was in professional circles. For example, an expedited treatment process may be seen as leaving the patient with insufficient time to effectively process and heal from trauma (Hofmann 36). However, this was speculative and preliminary research was extraordinarily promising. This only emphasized the necessity for further research in Hofmann’s opinion. (Hofmann 37) Hofmann was also preoccupied with LSD’s application to the ethics of dying. Pertaining especially to terminally-ill cancer patients, he hypothesized and hoped this might relieve them temporarily from their physical pain, and permanently from the fear of prospective death (Hofmann 38).\
            ',

            '$imgs/lsd_img_5.jpeg',

            'Though much of these assumptions were grounded in promising research and testing, they weren’t what occupied global headlines and hence transmitted to the masses. Hofmann’s joy of fathering LSD was extinguished as it transitioned from a drug explored as a remedy to one as an inebriant - especially in the United States, beginning in the late 1950s. In hindsight Hofmann saw it as inevitable that the more LSD was prematurely used as an inebriant, the more it would be painted in a poor, unearned light (Hofmann  39). Hofmann never advocated for free flowing use of LSD, but rather under expert medical guidance and supervision. He was highly conscious of the role of set and setting in the use of LSD: the ultimate difference between a positively transformative experience, and a potentially devastating one. As Hofmann saw it, LSD was no different to any other potent substance of which good could only come with informed use (Hofmann 48-50). He referenced mescaline to explain the blindside he experienced. There were many scientific publications on mescaline around the turn of the century but the use of this compound remained confined to medicine and experiments within artistic and literary circles. So, history gave him no cause to suspect any other fate for LSD (Hofmann 40).. Interestingly, mescaline and LSD actually faced criminal scheduling around the same time - despite having independent waves of interest as research subjects (“Altered Minds: Mescaline\'s Complicated History”). This speaks to the general diffusion of knowledge pertaining to psychedelic substances in the mid 20th century. The class of substances includes LSD, but is certainly not limited to it.',
            'Hofmann articulated, in his view, that bad actors coupled with social conditions led to the introduction of LSD to a countercultural public disenchanted with their present and susceptible to a drug that represented an escape from that reality. He cited Timothy Leary as a core fuel to this fire - the individual single most responsible for spreading LSD from the laboratory to counterculture (Hofmann 51). Timothy Leary was a Harvard psychology professor who had his first run-in with psilocybin mushrooms in Mexico in 1960 (“Timothy Leary”, Wikipedia). Leary has commented that he had “learned more about … (his) brain and its possibilities … [and] more about psychology in the five hours after taking mushrooms than … in the preceding 15 years of studying and doing research” (“Ram Dass, Fierce Grace”). ',
            'Leary went on to create the Harvard Psilocybin Project to analyse the effects of (the then legal) synthesised psilocybin on human subjects (psilocybin is produced during the synthesis of LSD - the process which Hofman pioneered and the substance which Sandoz willingly distributed to researchers outside their organisation). Leary experimented in treating alcoholism and reforming criminals - similar social good applications to the ones occupying Hofman’s imagination for the course of LSD (“Timothy Leary”, Wikipedia).',
            'However, Leary’s studies were riddled with controversy as to their scientific legitimacy and ethical practices. Follow-up studies suggested Leary and his colleagues over-reported improvements that could be attributed to psilocybin. Furthermore, Leary was condemned for taking psychedelics along with the research subjects and pressuring students to participate. He was fired from Harvard in 1963, but this was only the beginning of his journey (“Timothy Leary”, Harvard University).',
            'Leary was convinced of the results of his research and personal forays with psychedelics. He continued independent research in New York where he developed a philosophy around mind expansion and finding personal truth through LSD (“Timothy Leary”, Wikipedia). In 1965, he set out on a lecture tour to disseminate knowledge about LSD. Following several run-ins with the law, Leary began publicly promoting the use of psychedelic drugs which diffused far and wide through the media (“The Psychedelic Renaissance: Trip Reports from Timothy Leary, Michael Pollan, and Tao Lin”). Today his phrase “Turn on, tune in, drop out” has come to exemplify the LSD movement at the time. Not everyone perceived him well, but avid followers understood this to mean activate your neural equipment, interact harmoniously with your world, and be self-reliant. Opponents read this as “get stoned and abandon all constructive activity” (“How LSD Works”).  ',
            'Nevertheless, Leary’s advocacy created a wide enough and tight enough grip on many Americans disenchanted with capitalism, government, and war who went on to use psychedelics recreationally. Though other individuals can also be credited with diffusion of psychedelics into the mainstream (namely Ken Kesey, Richard Alpert - better known as Ram Dass, and Owsley Stanley), Leary was the most vocal advocate (“How LSD Works”). Though divisive, he had a conviction, charisma and boldness which generated attention and in the process he became a figure synonymous with both LSD and American counterculture.',
            'However, intentional and self-proclaimed psychedelic gurus weren’t the only catalyst. A tremendous amount of legitimate LSD research was produced during the 50s, coming from clinics and universities. However, it was reported - greatly elaborated - primarily in magazines and newspapers, rather than scientific journals which Hofmann believed were the appropriate medium for a pharmakon still new to the scientific community (Hofmann 41). Reporter narratives proliferated the notion that LSD could induce miraculous transformations in oneself. In an age before adequate laws were in place to appropriately restrict LSD’s use, these influences “soon led to broad diffusion of self-experimentation with the new drug” (Hofmann 42). ',
            'Hofmann believed this was no coincidence: America was ripe for such consumption. The 1960’s American reality was characterised by inescapable, excessive materialism; omnipresent industrialisation - and hence alienation from nature increasing too; growingly visible inequity; paralyzing gender norms; controversial wars (Hofmann 41). The left, and the youth - not prototyped by race, or socioeconomic class -  wanted change. LSD was not just viewed as a remedy but as a new lens through which to see and exist in the world. Accessing your consciousness, and transforming yourself was both a revolt against the present pretense and a daring embrace to enact tangible change. ',

            '$imgs/lsd_img_6.jpeg',

            'Hofmann was ultimately saddened by laws that were reactive, not proactive towards LSD. As recreational consumption increased, so did reports of trips gone wrong: speculation of genetic damage, fatal accidents, and even suicide (Hofmann 42). LSD was polarised, classed as a Schedule 1 drug and funding soon dried up for research amidst the negative stigma now attached to LSD. This stigma, in Hofmann’s opinion, was not a reflection of the danger of the drug more so than the danger of its misuse (Hofmann 45). As productive research froze, so did further exploration or realization of LSD’s benefits on the scale and capacity that Hofmann dreamed.',
            'Hofmann was a chemist at heart. He was blessed with the scientific imagination to breathe life into LSD - but not the foresight to imagine the paths that life would take him and his child. Locating his story in LSD’s compound history, from discovery to sharing his personal narrative with the world in 1979, illuminates how many forces have shaped human interaction with psychedelics. LSD is a force of chemistry as much as culture, politics and sociology. It seems that over this period, the loudest and most powerful voices ultimately dominated the most knowledgeable and sensible ones.',


        ]

    },
    {
        title: 'WWII: Caption',
        time: '1939 - 1945 ',
        bg: '/imgs/ww2_bg.jpeg',
        content: [
            'The idea of a truth serum has been ingrained within human culture for a while and scientific research regarding this serum started in 1916. However, it wasn’t until WWII that this scientific pursuit truly picked up. This section is specifically referring to the experiments conducted by Germany during the Nazi regime. Most of the experiments conducted by the Nazis were kept under wraps and the complete list of experiments was revealed after the war had ended. It is highly unlikely that the Allies knew that the Nazis were trying to find a truth serum. However, they were aware the Nazi’s were working with psychedelics. This was due to the British intelligence intercepting a telecommunication that requested a delivery of 50 grams of mescaline for interrogation purposes at the concentration camps Dachau and Auschwitz in mid-1942. Their specific aim was to eliminate the will of the person being examined. They did end up drawing secrets out from inmates, but overall, they had very different reactions to the doses. However, they concluded that mescaline was too unreliable to serve as a truth serum as the outcomes weren’t consistent (Passie).',

            'After the United States learned of this experiment, the search for their own serum began in earnest. Several parts of the US government participated in this search and created multiple projects to achieve this including Project BLUEBIRD, Project CHATTER, and Operation CASTIGATE (Passie). In 1953 all of these projects were combined to create the more well-known project MK-ULTRA. MK-ULTRA was run almost entirely by a chemist named Sidney Gottlieb. At the time the director of the CIA, Richard Helms, gave Gottlieb the freedom to do whatever he wanted. Stephen Kinzer, a journalist who spent several years investigating the project, said in an interview that “[MK-ULTRA] most sustained search in history for techniques of mind control” and that “[Sidney Gottlieb] had a license to kill. He was allowed to requisition human subjects across the United States and around the world and subject them to any kind of abuse that he wanted, even up to the level of it being fatal — yet nobody looked over his shoulder.” ',

            '$imgs/ww2_img_1.jpeg',

            'The CIA established several secret detention centers throughout Europe and East Asia in which they would capture enemy agents and other suspected persons or people who they defined as expendable. They would throw these individuals into cells and test a myriad of hallucinogens on them to understand and break the human mind. These experiments were very much a continuation of work that began in Nazi and Japanese concentration camps. In fact, the CIA hired many vivisectionists and the torturers who worked in Nazi and Japanese concentration camps. A specific example of this is as mentioned before, Nazi doctors had conducted extensive experiments with mescaline at the Dachau concentration camp, so the CIA hired these doctors who were involved in the experiment to advise them. MK-ULTRA didn’t just test these serums on reluctant enemies overseas, they also experimented on prisoners in the US who volunteered. Unfortunately, the CIA misinformed these prisoners stating that the experiment aimed at finding a cure for schizophrenia, when really, they were looking at long term reactions to drugs. One victim of this was crime boss Whitey Bulger who was given LSD every day for more than a year under the guise of finding a cure for schizophrenia. He said that he thought he was going insane. Most of the MK-ULTRA archives were destroyed by Gottlieb, so the full extent of this experiment is still unknown (Gross).',

        ]

    },
    {
        title: 'Central Mexico: Seeking the Magic Mushroom',
        time: '1950s',
        bg: '/imgs/mm_bg.jpeg',
        content: [
            '“Seeking the Magic Mushroom” details the experience of locating, researching, and using a hallucinogenic mushroom venerated by the Mixeteco people, an indigenous tribe located in Central Mexico. The article focused specifically on the Mixtecos religious use of the hallucinogenic mushroom. The mushrooms were not worshipped as a distinctly unique entity. Rather, they were highly valued due to their hallucinogenic qualities - qualities the Mixteco people interpreted as messages from God. Thus, the mushroom was seen as a tool, not as an idol. This article, after being published in the 1957 May Edition of Life Magazine, reintroduced hallucinogenic mushrooms to Western society. It was largely credited with popularizing “magic shrooms” as a recreational drug, specifically during the Counterculture Movement of the 1960s and 1970s.',

            'Author R. Gordon Wasson was dismayed by the popularization of these mushrooms as recreational drugs. His primary research interest was in the cultural and religious uses of hallucinogenic mushrooms - Wasson’s motivation for reporting on them was purely academic. In an interview with High Times Magazine, Wasson divulged that “I’m not proud of the wave of use by neophytes...who take mushrooms for a thrill” (Wasson). Wasson strongly disapproved of the recreational use of psychedelic mushrooms. He believed that regular use - or using it “for a thrill” - undermined its religious significance to the Mixtec people. Wasson shared the Mixtecos spiritual sentiment for the mushrooms and believed they may only be used with great care and consideration. He himself only consumed them for academic purposes. Ultimately, he regarded the recreational use of hallucinogenic mushrooms as irresponsible and distinctly incorrect. ',

            'Regardless, the popularization of the drug was likely due to Wasson’s fantastical descriptions of his psychedelic trips, as well as his adventure-esque style of writing. This writing style was likely a product of Wasson’s journalism background and an academic desire to describe the hallucinations as accurately as possible. ',
        ]

    },
    {
        title: 'Cold War: Caption',
        time: '1946 - 1990s',
        bg: '/imgs/cw_bg.jpeg',
        content: [

            'The Cold War was a prolonged period of tension between the U.S. and Soviet Union in their efforts to establish global supremacy. Occurring from the late 1940s to 1989, the war never saw direct combat between the two superpowers. Rather, the war was characterized by indirect “proxy wars,” as well as by espionage, propaganda, and arms building. Psychedelics interacted with war efforts in several ways.',

            'Drug use was widespread amongst American Vietnam soldiers, with “51 percent of the armed forces [having] smoked marijuana, 31 percent [having] used psychedelics, such as LSD” (Janos). It is possible that some of these soldiers were exposed to LSD and drug use as former members of the Counterculture Movement in America. However, the vast majority of them were not. In reality, the demographics of the two groups, Vietnam soldiers and Counterculture hippies, were quite different. Hippies generally comprised educated, white middle-class college students, while soldiers were predominately uneducated and working class individuals (Guilmartin 323). The military draft permitted college students to legally evade enlistment, allowing hippies to forefront counterculture movements throughout the country. In contrast, working young men were drafted, preventing them from participating in hippie culture in America. ',

            'Thus, the simultaneous use of psychedelics in Vietnam and America was not a result of Counterculture members split across continents. Rather, it was due to distinctly separate groups each seeking drugs as a means to experience alternate realities. For soldiers, it was a method to escape the terrors of war. For hippies, it was a way to reach an alternate route to enlightenment. The concurrent use of hallucinogens between these groups was an abstract connection, one that each side was not necessarily aware of. ',

        ]

    },
    {
        title: 'Counter Culture: Flesh of the Devil',
        time: '1960s - 1970s',
        bg: '/imgs/cc_bg.jpeg',
        content: [
            'The Counterculture Movement refers to a distinct cultural phenomenon in the United States during the mid-1960s to mid-1970s. The primary tenets of the movement were the rejection and reimagining of traditional social structures and established institutions. For example, many adopted anti-war and anti-capitalism sentiments, while advocating for refined attitudes regarding sexuality, gender roles, and drug use. Diverse populations participated - to some extent - in the movement. However, the most notable and most publicized were the “hippies:” communities that typically consisted of white, middle class college students. In their rejection of mainstream institutions, hippies often sought alternative routes to enlightenment. As a result, many used and experimented with drugs, notably marijuana, LSD, and psilocybin. Soon, these communities were characterized by their extensive drug use.',

            'These drugs, specifically LSD, played a significant role in the struggle between hippies and the established government and media. LSD, which was known to be used by hippie communities, was purposefully stigmatized and criminalized to suppress the deviant, anti-war beliefs of hippie communities. An example of this was the production and release of the 1967 film “LSD Flesh of the Devil:” an action movie in which a secret agent tracks down a crime lord scheming to take over the world with psychedelics (Mida).',

            'Concurrent with the beginning of the Counterculture Movement, the Vietnam War was nearing its tenth year of conflict. Hippies were distinctly opposed to the Vietnam and Cold War, possibly due to the ideologies that the war represented. The Cold War was largely an “ideological confrontation” - in order to oppose Soviet communism, many argued that the West required a “coherent ideology” (Cranston). The idea of a “coherent” or orderly culture was antithetical to the Counterculture’s devotion to opposing mainstream institutions. Thus, it was natural for hippies to be hostile toward organizations that advocated or represented traditional norms and control, such as the media and the government. Conversely, mass media and government targeted hippies due to their “radical” and dissenting beliefs. Thus, during this time, ideological confrontations did not only occur between the U.S. and Soviet Union. Rather, there was ideological conflict within the U.S. itself: between Counterculture ideals and traditional beliefs (represented by the media and government). It is not surprising that all available means, such as LSD, were used in the conflict between the contemporary and traditional. ',

            'Quote by Ehrlichman'

        ]

    },
    {
        title: 'Present Day',
        time: '2004 - Now ',
        bg: '/imgs/pd_bg.jpeg',
        content: [
            'While these substances have been criminalized for decades, we are now seeing a resurgence in positive outlook on psychedelic use, marked by Roland Griffith’s clinical studies of psilocybin treatment for terminally ill cancer patients (Griffiths, 2017). His lab was among the few clinical settings that were revived and received regulatory approval in 2000. Over the following several years, many landmark studies were published on the psychotherapeutic potential of psychedelics (specifically psilocybin), placing a firm stake in the ground in the medical community. It was discovered that psilocybin was effective for treating PTSD, major depressive disorder, anxiety, and alcoholism. Griffiths even published on the profound effects of mystical experiences on sustained meaning and spirituality. In 2019, he founded the Johns Hopkins Center for Psychedelic and Consciousness Research, which has a comprehensive focus on studying the workings of the mind using psychedelics (Psychedelic Timeline). Through DNA sequencing, researchers have discovered a method for mass producing psilocybin. For psychedelic treatments (including ketamine), set and setting are the main focus; these therapies are respectful of the volatility in psychedelic experience, and they are done with a trained therapist.',

            'Directly resulting from this chain of research, 2019 marked the year when several cities in the U.S. began decriminalizing psychedelics, including Santa Cruz, Denver, Ann Arbor, and D.C. Several states have been reviewing legislation to legalize these substances. In an especially progressive move, the whole state of Oregon has made psychedelic use legal (among heroine, cocaine, etc). In the state-legislated program called the “Oregon Model,” a facilitator is trained in both Western and Indigenous use of psychedelics (Mason, 2021). These are clear signs that there is a lively effort to decriminalize and integrate these substances safely into our culture, especially with growing demands to innovate on our treatment system for mental health. These events are even reflected in popular culture, there is an apparent renaissance on our hands—psychedelics have been the focus of many books, documentaries, podcasts. For example, the documentaries Fantastic Fungi and Have a Good Trip were recently released and discuss recreational, therapeutic, and spiritual use. For this work to continue, advocacy to influence public policy and management of drug and mental health stigma will play important roles in the balancing of entheogenic and scientific perspectives in the interest of consciousness studies.',

            'Mental health stigma',

            'Research initiatives and medical trials, especially assisted therapy',

            'Advocacy, legalization efforts, patents',

        ]

    }

]



export const themes = [
    {
        title: 'Governance and Politics',
        bg: '/imgs/gov_bg.jpeg',
        content: [
            'At many given times, the common consensus on psychedelics and the ethical standards applied to these substances has been dictated by prevailing governing bodies. The compound history of psychedelics reveals that when authorities (or authoritative figures and groups) hold a negative view of psychedelics this often translates into stigmatisation and/or criminalisation of the substances which trickles down to the common masses. Inversely, there have also been cultures that revered psychedelics as holy and also societies where psychedelics have been used as political tools. Thus, it is imperative to consider how these substances have been governed as their social positioning is often reflective of perspectives held by people in power.',
            'Throughout our timeline, be it at the dawn of the colonial era or just a century ago, psychedelics have faced criminalization and stigmatisation by association with the enemies of the state. We may have evolved from christendom to democracy, yet we see parallels between how the churches stigmatised  psychedelics to compete with each other , and how a US president criminalised psychedelics as a move against his  enemies: the antiwar left and black people.',
            '<Governance now>'
        ]
    },
    {
        title: 'Ethics in Grey Zones',
        content: [
            'Psychedelics have had a contentious relationship with ethics throughout history.  The compound history of psychedelics has influenced what we view as ethical today. It’s not that ethical standards have changed in a vacuum.',
            'As recently as the 1960s, we can trace how specific actors, like mainstream news outlets hungry for sensational content and self-proclaimed gurus of psychedelics, prematurely propelled psychedelic substances into the public eye. In a Western context, till this point psychedelics had been closely confined to scientific circles. Individuals in contact with the substances did so with caution for psychedelics’ capacity for harm.',
            'Being plunged into the mainstream is what redefined psychedelics, like LSD, from a remedy to an inebriant. As people started using psychedelics recreationally, misled by reports of the momentous power of psychedelics, bad trips began dominating the narrative around psychedelics. In the process, bad outcomes became inherently associated with the substances themselves, and shortly after psychedelics were classified and criminalized.',
            'This early eagerness by a select few to usher psychedelics from labs to the mainstream, and the resultant misuse of psychedelics by many, has shaped the higher ethical standards we have for psychedelic research and propagation today. This has enabled the current reemergence of such work. Here, we have only provided one relatively contemporary and Western-centric example connecting psychedelics and ethics. However, throughout psychedelic compound history, and in our research, other examples are also highlighted.'
        ]
    },
    {
        title: 'Adopting and Assuming Identities',
        content: [
            'Throughout their compound history, psychedelics have been used by various communities and populations of people. However, a notable trend is that psychedelics often adopt the identities of the individuals who use them. This is regardless of the user’s identity: whether they are viewed positively or negatively, whether they are highly admired or heavily stigmatized. Psychedelics will adopt the likeness of their users, whatever society deems that to be. However, this is not a simple one-way-street. Psychedelics themselves have their own characteristics and qualities. These traits pass on to the communities who use them, and influences how society at large understands these groups.',
            'Psychedelics and the Mixtec people',
            'Psychedelics and hippies',
        ]
    },
    {
        title: 'Science and Spirituality at Odds',
        content: [
            'Used sacramentally by Indigenous cultures as a gateway to a mystical plane of existence, psychedelics have been slippery substances to integrate into our colonial, scientific society. Recently, psychedelics have become increasingly considered by experts in mental health, mindfulness, and cognitive science to have tremendous potential to both treat neuroses and challenge long standing beliefs dwindling in utility. This recent movement is to contest perceptions of psychedelics forged during the ‘60s and ‘70s, during which psychedelics were seen as dangerous and were associated with anti-war hippies; thus, a panicked government backlash was sparked, eventually leading to the classification of psychedelics as “addictive” schedule I substances. The West has had a controversial, almost cyclic relationship with psychedelics. They were originally perceived as entheogens, substances used to bring forth the divine from within, but we cannot help but view them through a scientific lens - we disregard refined Indigenous practices in which psychedelics were used for healing and spiritual guidance. Current research is primarily focused on developing better treatments for mental disorders including PTSD, substance use disorder, depression, and anxiety. This is human-centered research, but the issue is that academia is still limited in funding and underdeveloped in paradigms. Hopefully, future focus will narrow in on the mystical experiences themselves that are richly complex and ripe with opportunity for research, allowing for a productive intertwinement of science and spirituality.'
        ]
    },
]







export const bib = [

    'Hofmann, Albert. “Chapter 1.” LSD: My Problem Child – Reflections on Sacred Drugs, Mysticism and Science (1979), MAPS, Multidisciplinary Association for Psychedelic Studies, Santa Cruz, CA, 2009, pp. 2–72.',
    '“LSD\'s Long, Strange Trip | Retro Report | The New York Times.” YouTube, 16 May 2016, https://www.youtube.com/watch?v=WouOr579mfY. Accessed 3 Nov. 2021',
    'Pollan, Michael. “Chapter One: A Renaissance.” How to Change Your Mind: The New Science of Psychedelics, Penguin Books, New York, NY, 2018, pp. 21–61.',
    'Papadokonstantakis, Stavros, et al. “Switzerland: The Success of Its Chemicals and Pharmaceuticals Industries.” CEP, Dec. 2013, pp. 31–34.',
    '“A History of the Pharmaceutical Industry.” Pharmaphorum, Pharmaphorum, 1 Sept. 2020, https://pharmaphorum.com/r-d/a_history_of_the_pharmaceutical_industry/.',
    '“A Formula for Success: Inside Swiss Pharma.” Pharmaceutical Technology, 13 June 2018, https://www.pharmaceutical-technology.com/features/formula-success-inside-swiss-pharma/.',
    'Hanley, Brian P., et al. “Review of Scientific Self-Experimentation: Ethics History, Regulation, Scenarios, and Views among Ethics Committees and Prominent Scientists.” Rejuvenation Research, vol. 22, no. 1, 19 Feb. 2019, pp. 31–42., https://doi.org/10.1089/rej.2018.2059.',
    'Lemle, Mickey, director. Ram Dass, Fierce Grace. Documentary, 2001.',
    '“Timothy Leary.” Wikipedia, Wikimedia Foundation, 19 Nov. 2021, https://en.wikipedia.org/wiki/Timothy_Leary.',
    'Timothy Leary, Harvard University, https://psychology.fas.harvard.edu/people/timothy-leary.',
    'Freeman, Shanna, and Nathan Chandler. “How LSD Works.” HowStuffWorks Science, HowStuffWorks, 27 Jan. 2020, https://science.howstuffworks.com/lsd7.htm.',
    'Witt, Emily, and Hua Hsu. “The Psychedelic Renaissance: Trip Reports from Timothy Leary, Michael Pollan, and Tao Lin.” The New Yorker, The New Yorker, 29 May 2018, https://www.newyorker.com/books/under-review/the-science-of-the-psychedelic-renaissance.',
    'Abbott, Alison. “Altered Minds: Mescaline\'s Complicated History.” Nature News, Nature Publishing Group, 20 May 2019, https://www.nature.com/articles/d41586-019-01571-2.',

]
